line-length = 100
target-version = "py310"
exclude = [
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".ruff_cache",
]
lint.select = ["E","F","I","UP","B","SIM"]
lint.ignore = ["E203","E501"]
lint.unfixable = ["F401"]

[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
