name: ci

on:
  push:
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync --dev

      - name: Ruff (lint, but ignore exit code)
        run: uv run ruff check . --exit-zero

      - name: Ruff format (non-blocking)
        run: uv run ruff format --check . || true

      - name: Mypy (non-blocking)
        run: uv run mypy . || true

      - name: Pytest (optional)
        run: echo "pytest skipped for now"
