name: ci

on:
  push:
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync --dev

      - name: Ruff
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Mypy
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest
